config/routes.rb
Rails.application.routes.draw do

  resources :monsters
  resources :teams
  resources :types
  root 'home#index'
  get 'admin', to: 'home#admin', as: 'admin'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#signup', as: 'signup'
  post 'signup', to: 'users#create'
  resources :users

  get 'auth/:provider/callback', to: 'users#facebook_create'

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  belongs_to :type
  belongs_to :team
  belongs_to :user
  # validation
  validates :name, presence: true
  validates :type_id, presence: true
  validates :team_id, presence: true
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :match_user, only: [:edit, :destroy]


  layout 'adminLayout'

  # GET /monsters
  def index
    # @monsters = Monster.all
    if is_admin?
      @monsters = Monster.all
    else
      # show new current user related all monster status
      @monsters=current_user.monsters
    end
  end

  # GET /monsters/1
  def show
  end

  # GET /monsters/new
  def new
    # @monster = Monster.new
    number_of_monster=current_user.monsters.count
    if (number_of_monster < 20)
      @monster = Monster.new
    else
      redirect_to monsters_path, :alert => 'You have made already 20 Monsters !'
    end
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  def create
    @monster = Monster.new(monster_params)

    if @monster.save
      redirect_to @monster, notice: 'Monster was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /monsters/1
  def update
    if @monster.update(monster_params)
      redirect_to @monster, notice: 'Monster was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /monsters/1
  def destroy
    @monster.destroy
    redirect_to monsters_url, notice: 'Monster was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_monster
    @monster = Monster.find(params[:id])
  end

  ## match the user
  def match_user

    if not is_admin?
      if not (current_user.id==set_monster.user_id)
        redirect_to monsters_path, alert: 'You do not have permission to access this section !'
      end
    end

  end


  # Only allow a trusted parameter "white list" through.
  def monster_params
    params.require(:monster).permit(:name, :type_id, :team_id, :user_id)
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_form.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <% if @monster.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @monster.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  </div>
</div>



<div class="col-lg-8 col-lg-offset-2">
  <section class="panel">
    <header class="panel-heading">
      Monster Forms
    </header>
    <div class="panel-body">
      <div class="position-center">

        <%= form_for @monster,html:{class: 'form-horizontal'} do |f| %>

            <div class="form-group">

              <%= f.label :name,class: 'col-lg-3 col-sm-4 control-label' %>
              <div class="col-lg-9 col-sm-8">
                <%= f.text_field :name,class: 'form-control' %>

              </div>
            </div>

            
            <div class="form-group">

              <%= f.label :type_id,class: 'col-lg-3 col-sm-4 control-label' %>
              <div class="col-lg-9 col-sm-8">
                <% if Type.all.empty? %>
                 <%= link_to 'Create Type At First',new_type_path,class:'btn btn-warning' %>

                 <% else %>
                 <%= f.collection_select :type_id,Type.all,:id, :name, {prompt: true},{class:'form-control'} %>
                <% end %>
              </div>
            </div>
            

            <div class="form-group">

              <%= f.label :team_id_id,class: 'col-lg-3 col-sm-4 control-label' %>
              <div class="col-lg-9 col-sm-8">
                <% if Team.all.empty? %>
                    <%= link_to 'Create Team At First',new_team_path,class:'btn btn-danger' %>
                    <% else %>
                <%= f.collection_select :team_id,current_user.teams,:id, :name, {prompt: true},{class:'form-control'} %>
                <% end %>
              </div>
            </div>


            <div class="form-group">

              <%= f.hidden_field :user_id,value: current_user.id %>

            </div>

            <div class="form-group">
              <div class="col-lg-offset-3 col-lg-10">

                <%= f.submit 'Submit',class:'btn btn-success',name:'new' %>
                <%= link_to 'Back', monsters_path,class:'btn btn-info' %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </section>

</div>

app/views/monsters/edit.html.erb
<% provide(:title, 'Edit Monster') %>
<h1>Editing Monster</h1>

<%= render 'form' %>

app/views/monsters/index.html.erb
<% provide(:title, 'Monsters') %>
<h1>Listing Monsters</h1>

<div><%= link_to 'New Monster', new_monster_path, class: 'btn btn-md btn-success' %></div>


<br>
<div class="row">
  <div class="col-sm-12">
    <section class="panel">
      <header class="panel-heading">
        Monster Table
      </header>
      <div class="panel-body">
        <div class="adv-table">
          <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Power</th>
              <th>Team</th>
              <th>Action 1</th>
              <th>Action 2</th>
              <th>Action 3</th>

            </tr>
            </thead>
            <tbody>
            <% @monsters.each do |monster| %>
                <tr>
                  <td><%= monster.name %></td>
                  <% if not monster.type.nil? %>
                      <td><%= monster.type.name %></td>
                      <td>

                        <% @power=monster.type.power %>
                        <% if @power==1 %>
                            <i class="fa fa-star" aria-hidden="false"> </i>
                        <% elsif @power==2 %>

                            <% 2.times do %>
                                <i class="fa fa-star" aria-hidden="false"> </i>
                            <% end %>

                        <% elsif @power==3 %>

                            <% 3.times do %>
                                <i class="fa fa-star" aria-hidden="false"> </i>
                            <% end %>

                        <% elsif @power==4 %>

                            <% 4.times do %>
                                <i class="fa fa-star" aria-hidden="false"> </i>
                            <% end %>

                        <% elsif @power==5 %>
                            <% 5.times do %>
                                <i class="fa fa-star" aria-hidden="false"> </i>
                            <% end %>

                        <% end %>


                      </td>
                  <% end %>

                  <% if not monster.team.nil? %>
                      <td><%= monster.team.name %></td>
                  <% end %>

                 <td><%= link_to 'Show', monster %></td>
                  <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
                  <td><%= link_to 'Destroy', monster, method: :delete, data: {confirm: 'Are you sure?'} %></td>
                </tr>
            <% end %>

            </tbody>
          </table>

        </div>
      </div>
    </section>
  </div>
</div>

app/views/monsters/new.html.erb
<% provide(:title, 'New Monster') %>
<h1>New Monster</h1>

<%= render 'form' %>

app/views/monsters/show.html.erb
<% provide(:title, 'Monster') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-6 col-lg-6 col-md-offset-3">
    <section class="panel">

      <header class="panel-heading">
        View User Information
      </header>

      <div class="panel-body">

        <div class="position-center">
          <p>
            <strong>Name:</strong>
            <%= @monster.name %>
          </p>

          <% if not @monster.type.nil? %>
          <p>
            <strong>Type:</strong>
            <%= @monster.type.name %>
          </p>

          <% end %>

          <% if not @monster.team.nil? %>
          <p>
            <strong>Type:</strong>
            <%= @monster.team.name %>
          </p>

          <% end %>

          <% if not @monster.type.nil? %>
          <p>
            <strong>Power:</strong>
            <% @power=@monster.type.power %>
            
            <% if @power==1 %>
                        <i class="fa fa-star" aria-hidden="false"> </i>
                    <% elsif @power==2 %>
                        
                        <% 2.times do %>
                        <i class="fa fa-star" aria-hidden="false"> </i>
                        <% end %>

                    <% elsif @power==3 %>
                        
                        <% 3.times do %>
                        <i class="fa fa-star" aria-hidden="false"> </i>
                        <% end %>

                    <% elsif @power==4 %>
                        
                        <% 4.times do %>
                        <i class="fa fa-star" aria-hidden="false"> </i>
                        <% end %>

                    <% elsif @power==5 %>
                        <% 5.times do %>
                        <i class="fa fa-star" aria-hidden="false"> </i>
                        <% end %>

            <% end %>



          </p>

          <% end %>
          

          


          <%= link_to 'Edit', edit_monster_path(@monster),class:'btn btn-info' %> |
          <%= link_to 'Back', monsters_path,class: 'btn btn-danger' %>


        </div>

      </div>

    </section>

  </div>
</div>