config/routes.rb
Rails.application.routes.draw do

  resources :monsters
  resources :teams
  resources :types
  root 'home#index'
  get 'admin', to: 'home#admin', as: 'admin'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#signup', as: 'signup'
  post 'signup', to: 'users#create'
  resources :users

  get 'auth/:provider/callback', to: 'users#facebook_create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :monsters
  has_many :teams
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

## for registration by facebook information
  ## for sign in
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'],uid: auth['uid']) ||      create_user_from_omniauth(auth)
  end

  ## for registration by facebook information
  def self.create_user_from_omniauth(auth)
    create!(provider: auth['provider'],uid: auth['uid'],name: auth['info']['name'],email: auth['info']['email'],password:'user123')
  end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:new, :destroy]


  layout 'adminLayout', except: :signup

  # get /users/
  def index
    @users = User.all
  end

  # get  /users/1
  def show
    @user = User.find(params[:id])
  end

  # get  /users/new
  def new
    @user = User.new
  end

  # post /users/create
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice: 'An user was successfully registered.'
    else
      render 'new'
    end
  end

  # get /users/1/edit
  def edit
  end

  # put /users/1/update
  def update
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  # delete /users/1
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end


  ## sign up for un-authorized people

  # get signup
  def signup
    if not logged_in?
      @user = User.new
    else
      redirect_to root_url, notice: 'Already signed in !'
    end
  end


  ## registration by facebook
  def facebook_create
    auth=request.env['omniauth.auth']
    session[:omniauth]=auth.except('extra')
    user=User.sign_in_from_omniauth(auth)
    session[:user_id]=user.id
    redirect_to admin_url, notice: 'You have logged in rubymon by facebook successfully !'
  end


  private


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/users/_error.html.erb
<div class="row">
<div class="col-lg-8 col-lg-offset-2">
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'users/error' %>
<div class="col-lg-8 col-lg-offset-2">
                <section class="panel">
                    <header class="panel-heading">
                         User Forms
                    </header>
                    <div class="panel-body">
                        <div class="position-center">
                            
                            <%= form_for @user,html:{class: 'form-horizontal'} do |f| %>
                            
                            <div class="form-group">
                                
                                <%= f.label :name,class: 'col-lg-3 col-sm-4 control-label' %>
                                <div class="col-lg-9 col-sm-8">
                                 <%= f.text_field :name,class: 'form-control' %>   
                                    
                                </div>
                            </div>
                                                                                   
                            <div class="form-group">
                                
                                <%= f.label :email,class: 'col-lg-3 col-sm-4 control-label' %>
                                <div class="col-lg-9 col-sm-8">
                                 <%= f.text_field :email,class: 'form-control' %>   
                                    
                                </div>
                            </div>
                            
                            
                            <div class="form-group">
                                
                                <%= f.label :password,class: 'col-lg-3 col-sm-4 control-label' %>
                                <div class="col-lg-9 col-sm-8">
                                 <%= f.password_field :password,class: 'form-control' %>   
                                    
                                </div>
                            </div>
                            
                            <div class="form-group">
                                
                                <%= f.label :password_confirmation,class: 'col-lg-3 col-sm-4 control-label' %>
                                <div class="col-lg-9 col-sm-8">
                                 <%= f.password_field :password_confirmation,class: 'form-control' %>   
                                    
                                </div>
                            </div>

                              <div class="form-group">
                                <div class="col-lg-offset-3 col-lg-10">
                                    <%= f.submit 'Submit',class:'btn btn-success' %>
                                    <%= link_to 'Back',users_path, class:'btn btn-info' %>
                                </div>
                            </div>
                        <% end %>
                        </div>
                    </div>
                </section>

            </div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>Listing Users</h1>

<div><%= link_to 'New User', new_user_path,class: 'btn btn-md btn-success' %></div>


<br>
<div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        User Table
                        </header>
                    <div class="panel-body">
                    <div class="adv-table">
                    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>E-mail</th>
                <th>Action 1</th>
                <th>Action 2</th>
                <th>Action 3</th>
                
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

        </tbody>
    </table>

                    </div>
                    </div>
                </section>
            </div>
        </div>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>

<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-6 col-lg-6 col-md-offset-3">
                <section class="panel">                    
                    <header class="panel-heading">
                        View User Information
                    </header>
                    
                    <div class="panel-body">
                        
                        <div class="position-center">
                          <p>
  <strong>First name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user),class:'btn btn-info' %> |
<%= link_to 'Back', users_path,class: 'btn btn-danger' %>
  
                            
                        </div>

                    </div>

                </section>

            </div>
</div>

app/views/users/signup.html.erb
<% provide(:title, 'Registration') %>
<%= render 'users/error' %>
<div class="container">

  <%= form_for @user, html: {class: "form-signin"} do |f| %>

      <h2 class="form-signin-heading">Sign Up</h2>

      <div class="login-wrap">
        <div class="user-login-info">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control',required: 'required' %>
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control',required: 'required' %>
          <%= f.label :password %><br>
          <%= f.password_field :password, class: 'form-control',required: 'required' %>
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, class: 'form-control',required: 'required' %>
          </div>
        <%= f.submit 'Registration', class: 'btn btn-login btn-block' %>


        <a href="<%= root_path %>auth/facebook" name='facebook' class="btn btn-facebook btn-block">Registration with Facebook</a>

        <div class="registration">Already Registered. <%= link_to 'Sign In', login_path %></div>

      </div>


  <% end %>

</div>