config/routes.rb
Rails.application.routes.draw do

  resources :monsters
  resources :teams
  resources :types
  root 'home#index'
  get 'admin', to: 'home#admin', as: 'admin'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#signup', as: 'signup'
  post 'signup', to: 'users#create'
  resources :users

  get 'auth/:provider/callback', to: 'users#facebook_create'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout 'layouts/adminLayout',except: :index
before_action :logged_in_user, only: :admin
  
  def index
  end

  def admin
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<% provide(:title,'Admin')%>
<div class="container">
  <div class="jumbotron">
    <h1>Rails Administration-Rubymon</h1>
    <p>Rubymon is a mobile app that allows players to catch, collect monsters, and eventually
      battle them. The game is played on a mobile app but we want to store user and monster
      information in the cloud. We need you to create a RESTful backend API to store and
      organize the monsters.</p>
  </div>
</div>

app/views/home/index.html.erb
<!--This parital will show sign in and sign up link in navigation bar in home page-->
<%= content_for :nav do %>

<% if current_user %>
<ul class="nav navbar-nav navbar-right">
<li><a href="#">Logged in as <b><%= current_user.name %></b></a></li>
 <li><%= link_to "Admin", admin_path %></li>
 <li><%= link_to "Log Out", logout_path %></li>
 </ul>
 <% else %>
 <ul class="nav navbar-nav navbar-right">
 <li><%= link_to "Sign In", login_path %></li>
 <li><%= link_to "Sign Up", signup_path %></li>
 </ul>
 <% end %>

<% end %>


<div class="container">
  <div class="jumbotron">
    <h1>Rubymon</h1>
    <p>Rubymon is a mobile app that allows players to catch, collect monsters, and eventually
      battle them. The game is played on a mobile app but we want to store user and monster
      information in the cloud. We need you to create a RESTful backend API to store and
      organize the monsters.</p>
  </div>
  
</div>